/* 
 * This code is taken form AfterShip's GitHub (https://github.com/AfterShip/aftership-sdk-net)
 * and slightly modified for our coding standards. 
 */

using System.ComponentModel;

namespace Nop.Plugin.Tracking.AfterShip.Infrastructure.Aftership.Enums
{
    public enum Iso3Country
    {
        [Description("NONE")]
        Null = 0,
        [Description("ABW")]
        Aruba,
        [Description("AFG")]
        Afghanistan,
        [Description("AGO")]
        Angola,
        [Description("AIA")]
        Anguilla,
        [Description("ALA")]
        AlandIslands,
        [Description("ALB")]
        Albania,
        [Description("AND")]
        Andorra,
        [Description("ARE")]
        UnitedArabEmirates,
        [Description("ARG")]
        Argentina,
        [Description("ARM")]
        Armenia,
        [Description("ASM")]
        AmericanSamoa,
        [Description("ATA")]
        Antarctica,
        [Description("ATF")]
        FrenchSouthernTerritories,
        [Description("ATG")]
        AntiguaAndBarbuda,
        [Description("AUS")]
        Australia,
        [Description("AUT")]
        Austria,
        [Description("AZE")]
        Azerbaijan,
        [Description("BDI")]
        Burundi,
        [Description("BEL")]
        Belgium,
        [Description("BEN")]
        Benin,
        [Description("BES")]
        BonaireSintEustatiusAndSaba,
        [Description("BFA")]
        BurkinaFaso,
        [Description("BGD")]
        Bangladesh,
        [Description("BGR")]
        Bulgaria,
        [Description("BHR")]
        Bahrain,
        [Description("BHS")]
        Bahamas,
        [Description("BIH")]
        BosniaAndHerzegovina,
        [Description("BLM")]
        SaintBarthelemy,
        [Description("BLR")]
        Belarus,
        [Description("BLZ")]
        Belize,
        [Description("BMU")]
        Bermuda,
        [Description("BOL")]
        BoliviaPlurinationalStateOf,
        [Description("BRA")]
        Brazil,
        [Description("BRB")]
        Barbados,
        [Description("BRN")]
        BruneiDarussalam,
        [Description("BTN")]
        Bhutan,
        [Description("BVT")]
        BouvetIsland,
        [Description("BWA")]
        Botswana,
        [Description("CAF")]
        CentralAfricanRepublic,
        [Description("CAN")]
        Canada,
        [Description("CCK")]
        CocosKeelingIslands,
        [Description("CHE")]
        Switzerland,
        [Description("CHL")]
        Chile,
        [Description("CHN")]
        China,
        [Description("CIV")]
        CoteDIvoire,
        [Description("CMR")]
        Cameroon,
        [Description("COD")]
        CongoDemocraticRepublic,
        [Description("COG")]
        Congo,
        [Description("COK")]
        CookIslands,
        [Description("COL")]
        Colombia,
        [Description("COM")]
        Comoros,
        [Description("CPV")]
        CaboVerde,
        [Description("CRI")]
        CostaRica,
        [Description("CUB")]
        Cuba,
        [Description("CUW")]
        Curacao,
        [Description("CXR")]
        ChristmasIsland,
        [Description("CYM")]
        CaymanIslands,
        [Description("CYP")]
        Cyprus,
        [Description("CZE")]
        CzechRepublic,
        [Description("DEU")]
        Germany,
        [Description("DJI")]
        Djibouti,
        [Description("DMA")]
        Dominica,
        [Description("DNK")]
        Denmark,
        [Description("DOM")]
        DominicanRepublic,
        [Description("DZA")]
        Algeria,
        [Description("ECU")]
        Ecuador,
        [Description("EGY")]
        Egypt,
        [Description("ERI")]
        Eritrea,
        [Description("ESH")]
        WesternSahara,
        [Description("ESP")]
        Spain,
        [Description("EST")]
        Estonia,
        [Description("ETH")]
        Ethiopia,
        [Description("FIN")]
        Finland,
        [Description("FJI")]
        Fiji,
        [Description("FLK")]
        FalklandIslandsMalvinas,
        [Description("FRA")]
        France,
        [Description("FRO")]
        FaroeIslands,
        [Description("FSM")]
        MicronesiaFederatedStates,
        [Description("GAB")]
        Gabon,
        [Description("GBR")]
        UnitedKingdom,
        [Description("GEO")]
        Georgia,
        [Description("GGY")]
        Guernsey,
        [Description("GHA")]
        Ghana,
        [Description("GIB")]
        Gibraltar,
        [Description("GIN")]
        Guinea,
        [Description("GLP")]
        Guadeloupe,
        [Description("GMB")]
        Gambia,
        [Description("GNB")]
        GuineaBissau,
        [Description("GNQ")]
        EquatorialGuinea,
        [Description("GRC")]
        Greece,
        [Description("GRD")]
        Grenada,
        [Description("GRL")]
        Greenland,
        [Description("GTM")]
        Guatemala,
        [Description("GUF")]
        FrenchGuiana,
        [Description("GUM")]
        Guam,
        [Description("GUY")]
        Guyana,
        [Description("HKG")]
        HongKong,
        [Description("HMD")]
        HeardIslandAndMcDonaldIslands,
        [Description("HND")]
        Honduras,
        [Description("HRV")]
        Croatia,
        [Description("HTI")]
        Haiti,
        [Description("HUN")]
        Hungary,
        [Description("IDN")]
        Indonesia,
        [Description("IMN")]
        IsleOfMan,
        [Description("IND")]
        India,
        [Description("IOT")]
        BritishIndianOceanTerritory,
        [Description("IRL")]
        Ireland,
        [Description("IRN")]
        IranIslamicRepublic,
        [Description("IRQ")]
        Iraq,
        [Description("ISL")]
        Iceland,
        [Description("ISR")]
        Israel,
        [Description("ITA")]
        Italy,
        [Description("JAM")]
        Jamaica,
        [Description("JEY")]
        Jersey,
        [Description("JOR")]
        Jordan,
        [Description("JPN")]
        Japan,
        [Description("KAZ")]
        Kazakhstan,
        [Description("KEN")]
        Kenya,
        [Description("KGZ")]
        Kyrgyzstan,
        [Description("KHM")]
        Cambodia,
        [Description("KIR")]
        Kiribati,
        [Description("KNA")]
        SaintKittsAndNevis,
        [Description("KOR")]
        KoreaRepublic,
        [Description("KWT")]
        Kuwait,
        [Description("LAO")]
        LaoPeoplesDemocraticRepublic,
        [Description("LBN")]
        Lebanon,
        [Description("LBR")]
        Liberia,
        [Description("LBY")]
        Libya,
        [Description("LCA")]
        SaintLucia,
        [Description("LIE")]
        Liechtenstein,
        [Description("LKA")]
        SriLanka,
        [Description("LSO")]
        Lesotho,
        [Description("LTU")]
        Lithuania,
        [Description("LUX")]
        Luxembourg,
        [Description("LVA")]
        Latvia,
        [Description("MAC")]
        Macao,
        [Description("MAF")]
        SaintMartinFrenchPart,
        [Description("MAR")]
        Morocco,
        [Description("MCO")]
        Monaco,
        [Description("MDA")]
        Moldova,
        [Description("MDG")]
        Madagascar,
        [Description("MDV")]
        Maldives,
        [Description("MEX")]
        Mexico,
        [Description("MHL")]
        MarshallIslands,
        [Description("MKD")]
        Macedonia,
        [Description("MLI")]
        Mali,
        [Description("MLT")]
        Malta,
        [Description("MMR")]
        Myanmar,
        [Description("MNE")]
        Montenegro,
        [Description("MNG")]
        Mongolia,
        [Description("MNP")]
        NorthernMarianaIslands,
        [Description("MOZ")]
        Mozambique,
        [Description("MRT")]
        Mauritania,
        [Description("MSR")]
        Montserrat,
        [Description("MTQ")]
        Martinique,
        [Description("MUS")]
        Mauritius,
        [Description("MWI")]
        Malawi,
        [Description("MYS")]
        Malaysia,
        [Description("MYT")]
        Mayotte,
        [Description("NAM")]
        Namibia,
        [Description("NCL")]
        NewCaledonia,
        [Description("NER")]
        Niger,
        [Description("NFK")]
        NorfolkIsland,
        [Description("NGA")]
        Nigeria,
        [Description("NIC")]
        Nicaragua,
        [Description("NIU")]
        Niue,
        [Description("NLD")]
        Netherlands,
        [Description("NOR")]
        Norway,
        [Description("NPL")]
        Nepal,
        [Description("NRU")]
        Nauru,
        [Description("NZL")]
        NewZealand,
        [Description("OMN")]
        Oman,
        [Description("PAK")]
        Pakistan,
        [Description("PAN")]
        Panama,
        [Description("PCN")]
        Pitcairn,
        [Description("PER")]
        Peru,
        [Description("PHL")]
        Philippines,
        [Description("PLW")]
        Palau,
        [Description("PNG")]
        PapuaNewGuinea,
        [Description("POL")]
        Poland,
        [Description("PRI")]
        PuertoRico,
        [Description("PRK")]
        KoreaDemocraticPeoplesRepublic,
        [Description("PRT")]
        Portugal,
        [Description("PRY")]
        Paraguay,
        [Description("PSE")]
        Palestine,
        [Description("PYF")]
        FrenchPolynesia,
        [Description("QAT")]
        Qatar,
        [Description("REU")]
        Reunion,
        [Description("ROU")]
        Romania,
        [Description("RUS")]
        RussianFederation,
        [Description("RWA")]
        Rwanda,
        [Description("SAU")]
        SaudiArabia,
        [Description("SDN")]
        Sudan,
        [Description("SEN")]
        Senegal,
        [Description("SGP")]
        Singapore,
        [Description("SGS")]
        SouthGeorgiaSouthSandwichIslands,
        [Description("SHN")]
        SaintHelenaAscensionAndTristanDaCunha,
        [Description("SJM")]
        SvalbardAndJanMayen,
        [Description("SLB")]
        SolomonIslands,
        [Description("SLE")]
        SierraLeone,
        [Description("SLV")]
        ElSalvador,
        [Description("SMR")]
        SanMarino,
        [Description("SOM")]
        Somalia,
        [Description("SPM")]
        SaintPierreAndMiquelon,
        [Description("SRB")]
        Serbia,
        [Description("SSD")]
        SouthSudan,
        [Description("STP")]
        SaoTomeAndPrincipe,
        [Description("SUR")]
        Suriname,
        [Description("SVK")]
        Slovakia,
        [Description("SVN")]
        Slovenia,
        [Description("SWE")]
        Sweden,
        [Description("SWZ")]
        Swaziland,
        [Description("SXM")]
        SintMaartenDutchPart,
        [Description("SYC")]
        Seychelles,
        [Description("SYR")]
        SyrianArabRepublic,
        [Description("TCA")]
        TurksAndCaicosIslands,
        [Description("TCD")]
        Chad,
        [Description("TGO")]
        Togo,
        [Description("THA")]
        Thailand,
        [Description("TJK")]
        Tajikistan,
        [Description("TKL")]
        Tokelau,
        [Description("TKM")]
        Turkmenistan,
        [Description("TLS")]
        TimorLeste,
        [Description("TON")]
        Tonga,
        [Description("TTO")]
        TrinidadAndTobago,
        [Description("TUN")]
        Tunisia,
        [Description("TUR")]
        Turkey,
        [Description("TUV")]
        Tuvalu,
        [Description("TWN")]
        Taiwan,
        [Description("TZA")]
        Tanzania,
        [Description("UGA")]
        Uganda,
        [Description("UKR")]
        Ukraine,
        [Description("UMI")]
        UnitedStatesMinorOutlyingIslands,
        [Description("URY")]
        Uruguay,
        [Description("USA")]
        UnitedStates,
        [Description("UZB")]
        Uzbekistan,
        [Description("VAT")]
        VaticanCityState,
        [Description("VCT")]
        SaintVincentAndGrenadines,
        [Description("VEN")]
        Venezuela,
        [Description("VGB")]
        VirginIslandsBritish,
        [Description("VIR")]
        VirginIslandsUs,
        [Description("VNM")]
        VietNam,
        [Description("VUT")]
        Vanuatu,
        [Description("WLF")]
        WallisAndFutuna,
        [Description("WSM")]
        Samoa,
        [Description("YEM")]
        Yemen,
        [Description("ZAF")]
        SouthAfrica,
        [Description("ZMB")]
        Zambia,
        [Description("ZWE")]
        Zimbabwe
    }
}